### ISSUE TITLE
Упаковать все сборки в один пакет

### ISSUE THREAD

**Issue by kulakovt** [DotNetRu/Auditor#10]
Сейчас [основной пакет библиотеки](https://www.nuget.org/packages/DotNetRu.Auditor/) собирается только с одной сборкой (Data). В разработке находится сборка Stoage, запланирована Validation. Они все должны быть включены в пакет.

Необходимо доработать существующую систему CI, для того чтобы она собирала пакет из всех (не тестовых) сборок, которые есть в репозитории.

**Comment by zetroot** [comment]
@kulakovt если я правильно понял задумку, то вроде бы так нельзя. 

> Currently, you must have a package per project if you have project-to-project dependencies.
[Отсюда](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack)

Есть разные костыли, но хорошее ли это решение? Может все таки разные пакеты - в одном абстракции, в других реализации, рядом валидация?

**Comment by kulakovt** [comment]
@zetroot 
Это ограничение `dotnet.exe`, через NuSpec можно.

Но я пришёл к выводу, что действительно всем сборкам нужен свой пакет. Но тогда не удобно будет добавлять много сборок к себе в приложение.

Поэтому я решил сделать [metapackage](https://andrewlock.net/the-microsoft-aspnetcore-all-metapackage-is-huge-and-thats-awesome-thanks-to-the-net-core-runtime-store-2/). И вот это просто мега-квест. Хотя и рекомендуемый официальный путь, но как это сделать красиво нигде не найти.

**Comment by zetroot** [comment]
Проглядел по диагонали - выглядит как возможное решение, но я так же нигде не видел короткого пути создания такого пакета.
