### ISSUE TITLE
Добавить индикатор покрытия тестами

### ISSUE THREAD

**Issue by kulakovt** [DotNetRu/Auditor#19]
Было бы интересно видеть покрытие тестами в проекте. Никакой самоцелью покрытие не является, просто полезный опыт и лишняя метрика для раздумий.

Стандартный шаблон тестового проекта в .NET 5 по умолчанию добавляет пакет `coverlet.collector`. Следует выяснить почему именно его и научиться настраивать этот пакет для CI.

Необходимо добавить плашку с актуальным покрытием в Readme.

**Comment by zetroot** [comment]
@kulakovt я экспериментировал с сбором метрики покрытия и в `Commune` и на работе (мы собираемся в Azure DevOps Server CI). В последнем случае мне пришлось использовать другой драйвер `coverlet.msbuild`, потому что он умеет собирать все репорты в один файл, а `coverlet.collector` создаёт по одному файлу на каждую тестовую сборку в один тестовый запуск.

[Codecov](https://about.codecov.io/) умеет парсить эти репорты, что называется, "из коробки". Никакой дополнительной настройки не потребовалось, для местного CI даже есть [готовый action](https://github.com/codecov/codecov-action).

Я года полтора назад пытался пробовать другой сервис - [Coveralls](https://coveralls.io/). Вроде бы все тоже самое, и так же есть [action](https://github.com/coverallsapp/github-action). Но что-то меня смутило, не могу сформулировать. Впрочем - никто не мешает использовать оба, правда?:-)

**Comment by kulakovt** [comment]
@zetroot , т.е. я правильно понимаю что `coverlet` собирает метрики, а `Codecov` строит из них уже отчёты?

**Comment by kulakovt** [comment]
А ещё интересно, есть ли интеграция всего этого дела с IDE? Чтобы именно в редакторе понимать какой код покрыт тестами, а какой нет.

**Comment by zetroot** [comment]
> @zetroot , т.е. я правильно понимаю что `coverlet` собирает метрики, а `Codecov` строит из них уже отчёты?

Ты абсолютно прав. + codecov умеет в "промежуточные" отчёты (как для [этого PR](https://github.com/DotNetRu/Commune/pull/146#issuecomment-863857647)). То есть у него есть там какой-то интеллектуальный трекинг с привязкой к жизни репозитория, а не просто хранилка xml-метрик.

> А ещё интересно, есть ли интеграция всего этого дела с IDE? Чтобы именно в редакторе понимать какой код покрыт тестами, а какой нет.

Так точно умеет `Rider`. Во первых, по запросу он считает что покрыто, а что нет и показывает красивые графики:
![test coverage report in rider](https://user-images.githubusercontent.com/30144288/124792079-53701280-df55-11eb-9f6c-aa534f53fac6.png)

И можно включить подсветку в редакторе.
![editor highlights code coverage](https://user-images.githubusercontent.com/30144288/124792151-6be02d00-df55-11eb-8fc3-febdc391106c.png)

Вроде бы такая же функциональность есть и в Visual Studio, но почему то по моим воспоминаниями только в Enterprise редакции. Хотя я могу и ошибаться.

**Comment by zetroot** [comment]
Тут правда есть вопросики, касаемо "кто как считает". Но общее представление о степени покрытия получить можно, я думаю (0% - слегка - половина - почти все - 100%)

**Comment by kulakovt** [comment]
Спасибо. Это сильно поможет.

Про Rider, у него есть родной `dotCover`. У меня вопрос был именно про `coverlet`. Может ли Rider так же (как и для `dotCover`) показывать отчёты от `coverlet`'а? Ибо настройки, интерпретация, заумность могут сильно отличаться у этих двух инструментов.

**Comment by zetroot** [comment]
А, я понял. Ты хочешь смотреть отчеты, собранные именно
`coverlet.collector` в IDE.
Такая фкнкциональность мне неизвестна.  Возможно есть плагин.

ср, 7 июл. 2021 г., 19:28 Anatoly Kulakov ***@***.***>:

**Comment by zetroot** [comment]
Насколько я понимаю всю эту историю, самая полезная часть - это проверка pr на то что он покрыт тестами, т.е. общее покрытие не уменьшится. Остальное - это хвастовство беджиком.

**Comment by kulakovt** [comment]
Интересно, а можно ли настроить правила, чтобы PR считался «плохим» если покрытие уменьшилось? :)

**Comment by zetroot** [comment]
Я такое видел в какой то репе. Там был прям check такой.

Если встречу опять - кину ссылку

**Comment by zetroot** [comment]
@kulakovt Нужно добавить защиту на master и потрбовать прохождение "чеков"
![изображение](https://user-images.githubusercontent.com/30144288/125955795-25117cea-e1d1-41fc-a058-847bd157091e.png)

**Comment by kulakovt** [comment]
@zetroot , добавил. Спасибо.
Испытаем на следующем пул-реквесте :)
